apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: bookstore-api
build:
  artifacts:
    - image: k3d-registry:46697/api
      jib:
        type: maven
        args:
          - -Pjib
deploy:
  kubectl:
    manifests:
      - kubernetes/deployment.yml
      - kubernetes/service.yml

portForward:
  - resourceType: deployment
    resourceName: api-deployment
    port: 8090
    localPort: 8090
  - resourceType: deployment
    resourceName: api-deployment
    port: 5005
    localPort: 5005
