apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: bookstore-pg
build:
  artifacts:
  - image: k3d-registry:46697/pg
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - src/main/kubernetes/*

portForward:
  - resourceType: deployment
    resourceName: pg-deployment
    port: 5432
    localPort: 5432